### PR TITLE
Implemented support of single resources

### PR DESCRIPTION
**Pull request by stalniy**
Sometimes there is a need to have single resources (e.g. session). And this single resources may have nested resources like

### CODE REVIEW

**Comment by jpillora** [comment]
So I presume this is for when: `/user/42/session/foo/7/` - no ID in between `session` and `foo` ? With this change, is the parent count still correct? Because throw an error if there are an invalid number of arguments (based off `numParents`)? Again could you please add this to the docs?

**Comment by stalniy** [comment]
Yes, you are right. But I forget about `@numParents`, I don't think that it's good to alter this variable when resource is single because that variable counts the number of parents in the structure. So, I think it would better to add another variable like `numIds`, wouldn't it?

**Comment by jpillora** [comment]
Okay so just had a quick look at the source again (haven't touched this project in a while). There's already a `numIds` used to temporarily store the number of non-object arguments (ids), this occurrence can be renamed to `providedIds`. Then `@numParents` can become `@expectedIds` (since it's only for counting ids anyhow) and then you can simply avoid incrementing when `isSingle`

**Comment by jpillora** [comment]
Made some edits

**Comment by stalniy** [comment]
done

**Comment by jpillora** [comment]
Awesome, thanks Sergiy, will take a look soon

**Comment by jpillora** [comment]
Hi Sergiy, I made an [examples/singleton-resource.html](https://github.com/jpillora/jquery.rest/blob/gh-pages/examples/singleton-resource.html) to test `isSingle` and it isn't working. Can you pull latest and check this?

A few things to note:
- I just added a [CONTRIBUTING.md](https://github.com/jpillora/jquery.rest/blob/gh-pages/CONTRIBUTING.md) guide
- This project is quite stable now so I've bumped it up to `v1.0.0`
- I'm making `autoClearCache` `true` by default as I think most people will expect this behaviour
- I'm using **Clear** instead of **Clean** to keep inline with the internal cache API

**Comment by stalniy** [comment]
The issue is that child inherits parent options:

``` coffee
@opts = inheritExtend @parent.opts, options
```

So, in your example `bazz` is also become a single resource because its parent `bar` has `isSingle` options set to `true`. It means that `isSingle` option shouldn't be inherited. 

The issue can be fixed like this:

``` coffee
# L:149
@opts.isSingle = 'isSingle' in options && options.isSingle
```

Are you ok with such solution or maybe you know better one?

**Comment by jpillora** [comment]
Ah right, ofcourse, since it's only one line, I'll commit that in tonight,
thanks

**Comment by jpillora** [comment]
Landed https://github.com/jpillora/jquery.rest/commit/01030ae8950ed6ebb6792ac6158c21ed8e6fe969

**Pull request merged**
